# Generated by Django 6.1.1 on 2026-10-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_add_exchange_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeprogram',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
